version: "3.8"

networks:
    myenglish:
        driver: "bridge"

services:
    postgres:
        image: postgres:10.2-alpine
        environment:
          POSTGRES_USER: ${POSTGRES_USER:-postgres}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
        ports:
          - "${POSTGRES_PORT:-5432}:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data
    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/symfony_docker
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - myenglish
        depends_on:
            - php
            - postgres
    php:
        container_name: php
        build:
          context: ./php
        ports:
            - '9000:9000'
        volumes:
            - ./app:/var/www/symfony_docker
        networks:
            - myenglish
volumes:
  postgres_data:
    driver: local
